describe('Login - Sistema', () => {

  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.visit('/signin')
    cy.login('demouser','testingisfun99')
  })

  context('Cenários positivos de venda', () => {

    it('Deve realizar a compra de um item Apple com o preço mais baixo', () => {
        cy.filtraPorMarca('Apple')
        cy.ordenaPreco('lowestprice')
        cy.validaItemEPreco('iPhone XR','499.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('499.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('iPhone XR')
        cy.validaSubtotal('499.00')
        cy.validarOrder('iPhone XR','499.00')
    })

    it('Deve realizar a compra de um item Apple com o preço mais alto', () => {
        cy.filtraPorMarca('Apple')
        cy.ordenaPreco('highestprice')
        cy.validaItemEPreco('iPhone 12 Pro Max','1099.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('1099.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('iPhone 12 Pro Max')
        cy.validaSubtotal('1099.00')
        cy.validarOrder('iPhone 12 Pro Max','1099.00')
    })

    it('Deve realizar a compra de um item Google com o preço mais baixo', () => {
        cy.filtraPorMarca('Google')
        cy.ordenaPreco('lowestprice')
        cy.validaItemEPreco('Pixel 2','399.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('399.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('Pixel 2')
        cy.validaSubtotal('399.00')
        cy.validarOrder('Pixel 2','399.00')
    })

    it('Deve realizar a compra de um item Google com o preço mais alto', () => {
        cy.filtraPorMarca('Google')
        cy.ordenaPreco('highestprice')
        cy.validaItemEPreco('Pixel 4','899.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('899.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('Pixel 4')
        cy.validaSubtotal('899.00')
        cy.validarOrder('Pixel 4','899.00')
    })

    it('Deve realizar a compra de um item Samsung com o preço mais baixo', () => {
        cy.filtraPorMarca('Samsung')
        cy.ordenaPreco('lowestprice')
        cy.validaItemEPreco('Galaxy S9','699.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('699.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('Galaxy S9')
        cy.validaSubtotal('699.00')
        cy.validarOrder('Galaxy S9','699.00')
    })

    it('Deve realizar a compra de um item Samsung com o preço mais alto', () => {
        cy.filtraPorMarca('Samsung')
        cy.ordenaPreco('highestprice')
        cy.validaItemEPreco('Galaxy S20 Ultra','1399.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('1399.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('Galaxy S20 Ultra')
        cy.validaSubtotal('1399.00')
        cy.validarOrder('Galaxy S20 Ultra','1399.00')
    })

    it('Deve realizar a compra de um item One Plus com o preço mais baixo', () => {
        cy.filtraPorMarca('OnePlus')
        cy.ordenaPreco('lowestprice')
        cy.validaItemEPreco('One Plus 6T','429.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('429.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('One Plus 6T')
        cy.validaSubtotal('429.00')
        cy.validarOrder('One Plus 6T','429.00')

    })

    it('Deve realizar a compra de um item OnePlus com o preço mais alto', () => {
        cy.filtraPorMarca('OnePlus')
        cy.ordenaPreco('highestprice')
        cy.validaItemEPreco('One Plus 8T','899.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('899.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('One Plus 8T')
        cy.validaSubtotal('899.00')
        cy.validarOrder('One Plus 8T','899.00')
    })

    it('Deve realizar a compra de 2 itens de diferentes marcas - OnePlus e Apple',()=>{
        cy.filtraPorMarca('OnePlus')
        cy.validaItemEPreco('One Plus 8','799.00')
        cy.adicionarAoCarrinho()
        cy.filtraPorMarca('Apple')
        cy.validaItemEPreco('iPhone 12','799.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('1598.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.downloadCompra()
        cy.validaItemCarrinhoParaFinalizar('One Plus 8')
        cy.validaItemCarrinhoParaFinalizar('iPhone 12')
        cy.validaSubtotal('1598.00')
    })

    it('Deve realizar a compra de 2 itens de diferentes marcas - Samsung e Google',()=>{
        cy.filtraPorMarca('Samsung')
        cy.validaItemEPreco('Galaxy S20','999.00')
        cy.adicionarAoCarrinho()
        cy.filtraPorMarca('Samsung')
        cy.filtraPorMarca('Google')
        cy.validaItemEPreco('Pixel 4','899.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('1898.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.validaItemCarrinhoParaFinalizar('Galaxy S20')
        cy.validaItemCarrinhoParaFinalizar('Pixel 4')
        cy.validaSubtotal('1898.00')
    })

    it('Deve realizar a compra de 2 itens iguais de mesma marca',()=>{
        cy.filtraPorMarca('Samsung')
        cy.validaItemEPreco('Galaxy S20','999.00')
        cy.adicionarAoCarrinho()
        cy.definirQuantidadeItens('2')
        cy.checkoutCarrinho('1998.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.validaSubtotal('1998.00')
        cy.validarOrder('Galaxy S20','1998.00')
    })

    it('Deve realizar a compra de 2 itens diferentes de mesma marca',()=>{
        cy.filtraPorMarca('Samsung')
        cy.ordenaPreco('lowestprice')
        cy.validaItemEPreco('Galaxy S9','699.00')
        cy.adicionarAoCarrinho()
        cy.retraiCarrinho()
        cy.ordenaPreco('highestprice')
        cy.validaItemEPreco('Galaxy S20 Ultra','1399.00')
        cy.adicionarAoCarrinho()
        cy.checkoutCarrinho('2098.00')
        cy.formularioCarrinho()
        cy.validaTexto('Your Order has been successfully placed.')
        cy.validaSubtotal('2098.00')
    })

  })
})